#!/usr/bin/env bash

work="${XDG_RUNTIME_DIR:-/run/user/$UID}"
base_folder="${work}/${0##*/}/${SteamAppId:-$SteamGameId}"

case "${1}" in
	"init")
		[[ -z ${STEAM_BASE_FOLDER} ]] && exit 0
		[[ ! -e "${base_folder}" ]] && mkdir -p "${base_folder}"

		echo "export SteamAppId=\"${SteamAppId}\"" >> "${base_folder}/env"
		echo "export SteamGameId=\"${SteamGameId}\"" >> "${base_folder}/env"
		echo "export STEAM_COMPAT_CLIENT_INSTALL_PATH=\"${STEAM_COMPAT_CLIENT_INSTALL_PATH}\"" >> "${base_folder}/env"
		echo "export STEAM_COMPAT_DATA_PATH=\"${STEAM_COMPAT_DATA_PATH}\"" >> "${base_folder}/env"
		echo "export STEAM_COMPAT_TOOL_PATHS=\"${STEAM_COMPAT_TOOL_PATHS}\"" >> "${base_folder}/env"
		echo "export STEAM_BASE_FOLDER=\"${STEAM_BASE_FOLDER}\"" >> "${base_folder}/env"

		shift ; "${@}"

		[[ -e "${base_folder}/env" ]] && rm -rf "${base_folder}"
	;;
	"run")
		[[ ! -e "${work}/${0##*/}/${2}/env" ]] && {
			echo "Arquivo "env" não encontrado."
			exit 1
		}
		[[ $# -lt 3 ]] && {
			echo "Falta argumentos, consulte o help."
			exit 1
		}
		source "${work}/${0##*/}/${2}/env"
		shift 2
		PROTON_STEAM="${STEAM_COMPAT_TOOL_PATHS%%:*}"
		"${PROTON_STEAM}/proton" run "${@}" 2>/dev/null
	;;
	"list")
		ls "${work}/${0##*/}/" 2>/dev/null || echo "Não encontrado, esta em execução?"
	;;
	"help"|"--help"|*)
		echo " ${0##*/}:
		init			Deve ser usado nas opções de inicialização do jogo. Cria o ambiente de execuçaõ.
					Ex: "${0##*/}" init %command%
		run <APPID> <EXE>	Usado para executar programas dentro do ambiente criado pelo "init".
					Ex: "${0##*/}" run 730 prog.exe
		list			Lista os programas em execução iniciados com o "init".
		help			Mostra esta ajuda.
		"
	;;
esac
