#!/usr/bin/env bash

# Diretórios base
# Runtime temporário do usuário
work="${XDG_RUNTIME_DIR:-/run/user/$UID}"
# Diretório base do script
base_folder="${work}/${0##*/}/${SteamAppId:-$SteamGameId}"

# Função principal, o uso do case facilita a leitura e a adição de novas opções
case "${1}" in
	"init")
		# Se usado fora da Steam, encerra
		[[ -z ${STEAM_BASE_FOLDER} ]] && exit 0
		[[ ! -e "${base_folder}" ]] && mkdir -p "${base_folder}"

		# Usado na Steam, prepara o ambiente para executar APPs externos
		echo "export SteamAppId=\"${SteamAppId}\"" >> "${base_folder}/env"
		echo "export SteamGameId=\"${SteamGameId}\"" >> "${base_folder}/env"
		echo "export STEAM_COMPAT_CLIENT_INSTALL_PATH=\"${STEAM_COMPAT_CLIENT_INSTALL_PATH}\"" >> "${base_folder}/env"
		echo "export STEAM_COMPAT_DATA_PATH=\"${STEAM_COMPAT_DATA_PATH}\"" >> "${base_folder}/env"
		echo "export STEAM_COMPAT_TOOL_PATHS=\"${STEAM_COMPAT_TOOL_PATHS}\"" >> "${base_folder}/env"
		echo "export STEAM_BASE_FOLDER=\"${STEAM_BASE_FOLDER}\"" >> "${base_folder}/env"

		# Continua a execução normal do jogo.
		shift ; "${@}"

		# Remove o ambiente criado para o jogo (Dura apenas enquanto o jogo executa)
		[[ -e "${base_folder}/env" ]] && rm -rf "${base_folder}"
	;;
	"run")
		[[ ! -e "${work}/${0##*/}/${2}/env" ]] && {
			echo "Arquivo "env" não encontrado."
			exit 1
		}
		[[ $# -lt 3 ]] && {
			echo "Falta argumentos, consulte o help."
			exit 1
		}
		# Carrega o ambiente
		source "${work}/${0##*/}/${2}/env"
		shift 2
		PROTON_STEAM="${STEAM_COMPAT_TOOL_PATHS%%:*}"
		# Executa a ferramenta externa (Pode usar comandos internos do Proton/WINE como: cmd, taskmgr, control etc.)
		"${PROTON_STEAM}/proton" run "${@}" 2>/dev/null
	;;
	"list")
		ls "${work}/${0##*/}/" 2>/dev/null || echo "Não encontrado, esta em execução?"
	;;
	"help"|"--help"|*)
		echo " ${0##*/}:
		init			Deve ser usado nas opções de inicialização do jogo. Cria o ambiente de execuçaõ.
					Ex: "${0##*/}" init %command%
		run <APPID> <EXE>	Usado para executar programas dentro do ambiente criado pelo "init".
					Ex: "${0##*/}" run 730 prog.exe
		list			Lista os programas em execução iniciados com o "init".
		help			Mostra esta ajuda.
		"
	;;
esac
